using motorsports_Domain.Entities;
using static motorsports_Domain.Constants.Constants;

namespace motorsports_Infrastructure.Seeding
{
    public class NationalityListSeeding
    {
        public static List<NationalityEntity> CountryList => new()
        {
            new() { Name = "Afghanistan", Code = "AFG", Continent = ContinentEnum.Asia, FlagUrl = "AFG.png" },
            new() { Name = "Albania", Code = "ALB", Continent = ContinentEnum.Europe, FlagUrl = "ALB.png" },
            new() { Name = "Algeria", Code = "DZA", Continent = ContinentEnum.Africa, FlagUrl = "DZA.png" },
            new() { Name = "Andorra", Code = "AND", Continent = ContinentEnum.Europe, FlagUrl = "AND.png" },
            new() { Name = "Angola", Code = "AGO", Continent = ContinentEnum.Africa, FlagUrl = "AGO.png" },
            new() { Name = "Argentina", Code = "ARG", Continent = ContinentEnum.SouthAmerica, FlagUrl = "ARG.png" },
            new() { Name = "Australia", Code = "AUS", Continent = ContinentEnum.Oceania, FlagUrl = "AUS.png" },
            new() { Name = "Austria", Code = "AUT", Continent = ContinentEnum.Europe, FlagUrl = "AUT.png" },
            new() { Name = "Bangladesh", Code = "BGD", Continent = ContinentEnum.Asia, FlagUrl = "BGD.png" },
            new() { Name = "Belarus", Code = "BLR", Continent = ContinentEnum.Europe, FlagUrl = "BLR.png" },
            new() { Name = "Belgium", Code = "BEL", Continent = ContinentEnum.Europe, FlagUrl = "BEL.png" },
            new() { Name = "Brazil", Code = "BRA", Continent = ContinentEnum.SouthAmerica, FlagUrl = "BRA.png" },
            new() { Name = "Bulgaria", Code = "BGR", Continent = ContinentEnum.Europe, FlagUrl = "BGR.png" },
            new() { Name = "Canada", Code = "CAN", Continent = ContinentEnum.NorthAmerica, FlagUrl = "CAN.png" },
            new() { Name = "Chile", Code = "CHL", Continent = ContinentEnum.SouthAmerica, FlagUrl = "CHL.png" },
            new() { Name = "China", Code = "CHN", Continent = ContinentEnum.Asia, FlagUrl = "CHN.png" },
            new() { Name = "Colombia", Code = "COL", Continent = ContinentEnum.SouthAmerica, FlagUrl = "COL.png" },
            new() { Name = "Croatia", Code = "HRV", Continent = ContinentEnum.Europe, FlagUrl = "HRV.png" },
            new() { Name = "Cuba", Code = "CUB", Continent = ContinentEnum.NorthAmerica, FlagUrl = "CUB.png" },
            new() { Name = "Czech Republic", Code = "CZE", Continent = ContinentEnum.Europe, FlagUrl = "CZE.png" },
            new() { Name = "Denmark", Code = "DNK", Continent = ContinentEnum.Europe, FlagUrl = "DNK.png" },
            new() { Name = "Egypt", Code = "EGY", Continent = ContinentEnum.Africa, FlagUrl = "EGY.png" },
            new() { Name = "Ethiopia", Code = "ETH", Continent = ContinentEnum.Africa, FlagUrl = "ETH.png" },
            new() { Name = "Finland", Code = "FIN", Continent = ContinentEnum.Europe, FlagUrl = "FIN.png" },
            new() { Name = "France", Code = "FRA", Continent = ContinentEnum.Europe, FlagUrl = "FRA.png" },
            new() { Name = "Germany", Code = "DEU", Continent = ContinentEnum.Europe, FlagUrl = "DEU.png" },
            new() { Name = "Greece", Code = "GRC", Continent = ContinentEnum.Europe, FlagUrl = "GRC.png" },
            new() { Name = "Hungary", Code = "HUN", Continent = ContinentEnum.Europe, FlagUrl = "HUN.png" },
            new() { Name = "Iceland", Code = "ISL", Continent = ContinentEnum.Europe, FlagUrl = "ISL.png" },
            new() { Name = "India", Code = "IND", Continent = ContinentEnum.Asia, FlagUrl = "IND.png" },
            new() { Name = "Indonesia", Code = "IDN", Continent = ContinentEnum.Asia, FlagUrl = "IDN.png" },
            new() { Name = "Iran", Code = "IRN", Continent = ContinentEnum.Asia, FlagUrl = "IRN.png" },
            new() { Name = "Iraq", Code = "IRQ", Continent = ContinentEnum.Asia, FlagUrl = "IRQ.png" },
            new() { Name = "Ireland", Code = "IRL", Continent = ContinentEnum.Europe, FlagUrl = "IRL.png" },
            new() { Name = "Israel", Code = "ISR", Continent = ContinentEnum.Asia, FlagUrl = "ISR.png" },
            new() { Name = "Italy", Code = "ITA", Continent = ContinentEnum.Europe, FlagUrl = "ITA.png" },
            new() { Name = "Japan", Code = "JPN", Continent = ContinentEnum.Asia, FlagUrl = "JPN.png" },
            new() { Name = "Kenya", Code = "KEN", Continent = ContinentEnum.Africa, FlagUrl = "KEN.png" },
            new() { Name = "Malaysia", Code = "MYS", Continent = ContinentEnum.Asia, FlagUrl = "MYS.png" },
            new() { Name = "Mexico", Code = "MEX", Continent = ContinentEnum.NorthAmerica, FlagUrl = "MEX.png" },
            new() { Name = "Netherlands", Code = "NLD", Continent = ContinentEnum.Europe, FlagUrl = "NLD.png" },
            new() { Name = "New Zealand", Code = "NZL", Continent = ContinentEnum.Oceania, FlagUrl = "NZL.png" },
            new() { Name = "Nigeria", Code = "NGA", Continent = ContinentEnum.Africa, FlagUrl = "NGA.png" },
            new() { Name = "Norway", Code = "NOR", Continent = ContinentEnum.Europe, FlagUrl = "NOR.png" },
            new() { Name = "Pakistan", Code = "PAK", Continent = ContinentEnum.Asia, FlagUrl = "PAK.png" },
            new() { Name = "Peru", Code = "PER", Continent = ContinentEnum.SouthAmerica, FlagUrl = "PER.png" },
            new() { Name = "Philippines", Code = "PHL", Continent = ContinentEnum.Asia, FlagUrl = "PHL.png" },
            new() { Name = "Poland", Code = "POL", Continent = ContinentEnum.Europe, FlagUrl = "POL.png" },
            new() { Name = "Portugal", Code = "PRT", Continent = ContinentEnum.Europe, FlagUrl = "PRT.png" },
            new() { Name = "Romania", Code = "ROU", Continent = ContinentEnum.Europe, FlagUrl = "ROU.png" },
            new() { Name = "Russia", Code = "RUS", Continent = ContinentEnum.Europe, FlagUrl = "RUS.png" },
            new() { Name = "Saudi Arabia", Code = "SAU", Continent = ContinentEnum.Asia, FlagUrl = "SAU.png" },
            new() { Name = "Serbia", Code = "SRB", Continent = ContinentEnum.Europe, FlagUrl = "SRB.png" },
            new() { Name = "Singapore", Code = "SGP", Continent = ContinentEnum.Asia, FlagUrl = "SGP.png" },
            new() { Name = "Slovakia", Code = "SVK", Continent = ContinentEnum.Europe, FlagUrl = "SVK.png" },
            new() { Name = "Slovenia", Code = "SVN", Continent = ContinentEnum.Europe, FlagUrl = "SVN.png" },
            new() { Name = "South Africa", Code = "ZAF", Continent = ContinentEnum.Africa, FlagUrl = "ZAF.png" },
            new() { Name = "South Korea", Code = "KOR", Continent = ContinentEnum.Asia, FlagUrl = "KOR.png" },
            new() { Name = "Spain", Code = "ESP", Continent = ContinentEnum.Europe, FlagUrl = "ESP.png" },
            new() { Name = "Sweden", Code = "SWE", Continent = ContinentEnum.Europe, FlagUrl = "SWE.png" },
            new() { Name = "Switzerland", Code = "CHE", Continent = ContinentEnum.Europe, FlagUrl = "CHE.png" },
            new() { Name = "Syria", Code = "SYR", Continent = ContinentEnum.Asia, FlagUrl = "SYR.png" },
            new() { Name = "Taiwan", Code = "TWN", Continent = ContinentEnum.Asia, FlagUrl = "TWN.png" },
            new() { Name = "Tanzania", Code = "TZA", Continent = ContinentEnum.Africa, FlagUrl = "TZA.png" },
            new() { Name = "Thailand", Code = "THA", Continent = ContinentEnum.Asia, FlagUrl = "THA.png" },
            new() { Name = "Turkey", Code = "TUR", Continent = ContinentEnum.Asia, FlagUrl = "TUR.png" },
            new() { Name = "Uganda", Code = "UGA", Continent = ContinentEnum.Africa, FlagUrl = "UGA.png" },
            new() { Name = "Ukraine", Code = "UKR", Continent = ContinentEnum.Europe, FlagUrl = "UKR.png" },
            new() { Name = "United Arab Emirates", Code = "ARE", Continent = ContinentEnum.Asia, FlagUrl = "ARE.png" },
            new() { Name = "United Kingdom", Code = "GBR", Continent = ContinentEnum.Europe, FlagUrl = "GBR.png" },
            new() { Name = "United States", Code = "USA", Continent = ContinentEnum.NorthAmerica, FlagUrl = "USA.png" },
            new() { Name = "Uruguay", Code = "URY", Continent = ContinentEnum.SouthAmerica, FlagUrl = "URY.png" },
            new() { Name = "Uzbekistan", Code = "UZB", Continent = ContinentEnum.Asia, FlagUrl = "UZB.png" },
            new() { Name = "Venezuela", Code = "VEN", Continent = ContinentEnum.SouthAmerica, FlagUrl = "VEN.png" },
            new() { Name = "Vietnam", Code = "VNM", Continent = ContinentEnum.Asia, FlagUrl = "VNM.png" },
            new() { Name = "Yemen", Code = "YEM", Continent = ContinentEnum.Asia, FlagUrl = "YEM.png" },
            new() { Name = "Zambia", Code = "ZMB", Continent = ContinentEnum.Africa, FlagUrl = "ZMB.png" },
            new() { Name = "Zimbabwe", Code = "ZWE", Continent = ContinentEnum.Africa, FlagUrl = "ZWE.png" },
        };
    }
}
