@motorsports-API_HostAddress = https://localhost:7016

GET {{motorsports-API_HostAddress}}/api/driver

###

GET {{motorsports-API_HostAddress}}/api/person/drivers

###

GET {{motorsports-API_HostAddress}}/api/person/drivers

###
